"""agrega campos de metricas a forecasts

Revision ID: d6d09177c84a
Revises: 
Create Date: 2026-04-22 16:22:07.494524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d09177c84a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('mae', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rmse', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mape', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('smape', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_column('smape')
        batch_op.drop_column('mape')
        batch_op.drop_column('rmse')
        batch_op.drop_column('mae')
        batch_op.drop_column('modelo')

    # ### end Alembic commands ###
